name: CI Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          # shallow clone disabled as recommended by SonarCLoud - https://github.com/marketplace/actions/sonarcloud-scan
          fetch-depth: 0
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup .Net Core 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore with .Net Core
        run: dotnet restore
      - name: Build with .Net Core
        run: dotnet build --no-restore --configuration Release
      - name: Test with .Net Core
        run: dotnet test --no-build --nologo --configuration Release
# TODO configure?
#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          args: >
#            -Dsonar.organization=daveTCode-github
#            -Dsonar.projectKey=FreshdeskApiDotnet
#            -Dsonar.verbose=true


  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          # shallow clone disabled as recommended by SonarCLoud - https://github.com/marketplace/actions/sonarcloud-scan
          fetch-depth: 0
      - name: Setup .Net Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup .Net Core 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Tool restore with .Net Core
        run: dotnet tool restore
      - name: .Net Format
        run: dotnet format --check -v diag
