name: PR Check Up

on:
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          # shallow clone disabled as recommended by SonarCLoud - https://github.com/marketplace/actions/sonarcloud-scan
          fetch-depth: 0
      - name: Setup .Net Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup .Net Core 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore with .Net Core
        run: dotnet restore
      - name: Build with .Net Core
        run: dotnet build --no-restore --configuration Release
      - name: Test with .Net Core
        run: dotnet test --no-build --nologo --configuration Release

  code-style:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          # shallow clone disabled as recommended by SonarCLoud - https://github.com/marketplace/actions/sonarcloud-scan
          fetch-depth: 0
      - name: Setup .Net Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup .Net Core 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Tool restore with .Net Core
        run: dotnet tool restore
      - name: .Net Format
        run: dotnet format --check -v diag
